services:
  otpinstan:
    build: .
    container_name: otpinstan
    restart: unless-stopped
    ports:
      - "8032:8032"
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ./main.py:/app/main.py
      - ./app:/app/app
      - otpinstan_data:/app/data

volumes:
  otpinstan_data:
